Repository twilio/twilio-verify-android, pull requests merged in 2021-11, with the labels that each got.

#192 [22998] Support notification platform "none"
  README.md
  sample/src/main/java/com/twilio/verify/sample/model/CreateFactorData.kt
  sample/src/main/java/com/twilio/verify/sample/view/factors/create/CreateFactorFragment.kt
  sample/src/main/res/layout/fragment_create_factor.xml
  sample/src/main/res/values/strings.xml
  verify/src/main/java/com/twilio/verify/domain/factor/FactorFacade.kt
  verify/src/main/java/com/twilio/verify/domain/factor/FactorMapper.kt
  verify/src/main/java/com/twilio/verify/domain/factor/PushFactory.kt
  verify/src/main/java/com/twilio/verify/domain/factor/models/PushFactor.kt
  verify/src/main/java/com/twilio/verify/models/PushFactorPayload.kt
  verify/src/main/java/com/twilio/verify/models/UpdatePushFactorPayload.kt
  verify/src/test/java/com/twilio/verify/domain/factor/FactorFacadeTest.kt
  verify/src/test/java/com/twilio/verify/domain/factor/PushFactoryTest.kt
Labels: enhancement, DO NOT MERGE YET

#194 [21769] Add contributing.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#195 Version 0.5.0
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  sample/src/main/java/com/twilio/verify/sample/model/CreateFactorData.kt
  sample/src/main/java/com/twilio/verify/sample/view/factors/create/CreateFactorFragment.kt
  sample/src/main/res/layout/fragment_create_factor.xml
  sample/src/main/res/values/strings.xml
  verify/src/main/java/com/twilio/verify/domain/factor/FactorFacade.kt
  verify/src/main/java/com/twilio/verify/domain/factor/FactorMapper.kt
  verify/src/main/java/com/twilio/verify/domain/factor/PushFactory.kt
  verify/src/main/java/com/twilio/verify/domain/factor/models/PushFactor.kt
  verify/src/main/java/com/twilio/verify/models/PushFactorPayload.kt
  verify/src/main/java/com/twilio/verify/models/UpdatePushFactorPayload.kt
  verify/src/test/java/com/twilio/verify/domain/factor/FactorFacadeTest.kt
  verify/src/test/java/com/twilio/verify/domain/factor/PushFactoryTest.kt
Labels: enhancement
